export const FoodList = [
  { id: 1, foodName: "Pizza" },
  { id: 2, foodName: "Burger" },
  { id: 3, foodName: "Pasta" },
  { id: 4, foodName: "Salad" },
  { id: 5, foodName: "Sushi" },
  { id: 6, foodName: "Tacos" },
  { id: 7, foodName: "Steak" },
  { id: 8, foodName: "Sandwich" },
  { id: 9, foodName: "Soup" },
  { id: 10, foodName: "Ice Cream" },
  { id: 11, foodName: "French Fries" },
  { id: 12, foodName: "Hot Dog" },
  { id: 13, foodName: "Fried Chicken" },
  { id: 14, foodName: "Lasagna" },
  { id: 15, foodName: "Omelette" },
  { id: 16, foodName: "Pancakes" },
  { id: 17, foodName: "Waffles" },
  { id: 18, foodName: "Ramen" },
  { id: 19, foodName: "Dumplings" },
  { id: 20, foodName: "Curry" },
  { id: 21, foodName: "Chili" },
  { id: 22, foodName: "Nachos" },
  { id: 23, foodName: "Spring Rolls" },
  { id: 24, foodName: "Pho" },
  { id: 25, foodName: "Falafel" },
  { id: 26, foodName: "Quesadilla" },
  { id: 27, foodName: "Barbecue" },
  { id: 28, foodName: "Fajitas" },
  { id: 29, foodName: "Paella" },
  { id: 30, foodName: "Burrito" },
  { id: 31, foodName: "Macaroni and Cheese" },
  { id: 32, foodName: "Grilled Cheese" },
  { id: 33, foodName: "Chow Mein" },
  { id: 34, foodName: "Ceviche" },
  { id: 35, foodName: "Gnocchi" },
  { id: 36, foodName: "Meatballs" },
  { id: 37, foodName: "Fried Rice" },
  { id: 38, foodName: "Calzone" },
  { id: 39, foodName: "Pierogi" },
  { id: 40, foodName: "Lobster" },
  { id: 41, foodName: "Shrimp Scampi" },
  { id: 42, foodName: "Clam Chowder" },
  { id: 43, foodName: "Fish and Chips" },
  { id: 44, foodName: "Bruschetta" },
  { id: 45, foodName: "Gumbo" },
  { id: 46, foodName: "Jambalaya" },
  { id: 47, foodName: "Baked Ziti" },
  { id: 48, foodName: "Stuffed Peppers" },
  { id: 49, foodName: "Chicken Parmesan" },
  { id: 50, foodName: "Pulled Pork" },
  { id: 51, foodName: "Poutine" },
  { id: 52, foodName: "Beef Stroganoff" },
  { id: 53, foodName: "Crab Cakes" },
  { id: 54, foodName: "Avocado Toast" },
  { id: 55, foodName: "Cobb Salad" },
  { id: 56, foodName: "Chicken Wings" },
  { id: 57, foodName: "Sloppy Joes" },
  { id: 58, foodName: "Shepherd's Pie" },
  { id: 59, foodName: "Ratatouille" },
  { id: 60, foodName: "Shakshuka" },
  { id: 61, foodName: "Tamales" },
  { id: 62, foodName: "Beef Wellington" },
  { id: 63, foodName: "Risotto" },
  { id: 64, foodName: "Moussaka" },
  { id: 65, foodName: "Pad Thai" },
  { id: 66, foodName: "Samosa" },
  { id: 67, foodName: "Empanadas" },
  { id: 68, foodName: "Goulash" },
  { id: 69, foodName: "Chimichanga" },
  { id: 70, foodName: "Eggplant Parmesan" },
  { id: 71, foodName: "Shawarma" },
  { id: 72, foodName: "Biryani" },
  { id: 73, foodName: "Kebab" },
  { id: 74, foodName: "Bangers and Mash" },
  { id: 75, foodName: "Spanakopita" },
  { id: 76, foodName: "Tortellini" },
  { id: 77, foodName: "Focaccia" },
  { id: 78, foodName: "Baklava" },
  { id: 79, foodName: "Churros" },
  { id: 80, foodName: "Eclairs" },
  { id: 81, foodName: "Tiramisu" },
  { id: 82, foodName: "Crepes" },
  { id: 83, foodName: "Brownies" },
  { id: 84, foodName: "Cheesecake" },
  { id: 85, foodName: "Pecan Pie" },
  { id: 86, foodName: "Banana Bread" },
  { id: 87, foodName: "Apple Pie" },
  { id: 88, foodName: "Chocolate Cake" },
  { id: 89, foodName: "Donuts" },
  { id: 90, foodName: "Muffins" },
  { id: 91, foodName: "Croissants" },
  { id: 92, foodName: "Cupcakes" },
  { id: 93, foodName: "Cinnamon Rolls" },
  { id: 94, foodName: "Macarons" },
  { id: 95, foodName: "Fruit Tart" },
  { id: 96, foodName: "Gelato" },
  { id: 97, foodName: "Pudding" },
  { id: 98, foodName: "Trifle" },
  { id: 99, foodName: "Popsicles" },
  { id: 100, foodName: "Mochi" },
];
